import { NeoPixelObject } from '@/components/devices/NeoPixels/interfaces';

const neoPixelsMockData: { [key: number]: NeoPixelObject } = {
  1: {
    remote_name: 'Neo Pixel 1',
    name: 'NeoPixel 1',
    reboots: 0,
    mqtt_id: 1,
    device_type_name: 'neo_pixel',
    tags: [1],
    last_seen: null,
    last_update_sent: null,
    plugin: {
      on: true,
      twinkle: true,
      all_twinkle_colors_are_current: true,
      scheduled_palette_rotation: false,
      transform: true,
      ms: 5,
      brightness: 127,
      palette: [
        '#0099FF',
        '#0099FF',
        '#00FF99',
        '#9900FF',
        '#9900FF',
        '#99FF00',
        '#FF9900',
        '#0099FF',
        '#00FF99',
      ],
      pir_enabled: true,
      pir_armed: true,
      pir_timeout: 10,
    },
  },
  2: {
    remote_name: 'Neo Pixel 2',
    name: 'NeoPixel 2',
    reboots: 17,
    mqtt_id: 2,
    device_type_name: 'neo_pixel',
    tags: [1],
    last_seen: null,
    last_update_sent: null,
    plugin: {
      on: false,
      twinkle: false,
      all_twinkle_colors_are_current: false,
      transform: false,
      white: true,
      ms: 31,
      brightness: 55,
      scheduled_palette_rotation: true,
      palette: [
        '#0099FF',
        '#FF0099',
        '#99FF00',
        '#FF9900',
        '#9900FF',
        '#00FF99',
        '#0099FF',
        '#99FF00',
        '#9900FF',
      ],
      timeout: 10,
    },
  },
};

export default neoPixelsMockData;
